"""
FPL Intel — Load Model & Predict from CSV

Run features.py first to generate the CSV, then run this.
"""
import sqlite3
import argparse
import pickle
import warnings
import numpy as np
import pandas as pd
import os

from ml.features import feature_engineering
warnings.filterwarnings("ignore")

# Point to the model generated by train.py at the project root
MODEL_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "models", "fpl_xgboost.pkl"))

def predict_points(query):
    try:
        with open(MODEL_PATH, "rb") as f:
            bundle = pickle.load(f)
        
        model        = bundle["model"]        # Pipeline (StandardScaler + XGBoost)
        feature_cols = bundle["feature_cols"] # Expected feature columns
        imputer      = bundle["imputer"]      # Imputer for missing values
        
        conn = sqlite3.connect("fpl_intel.db")

        players_name  = pd.read_sql("SELECT web_name FROM players",  conn)["web_name"].values.tolist()
        conn.close()
        
        found = ""
        for player in players_name:
            if player.lower() in query.lower():
                found = player
                break;

        if(found == ""):
            return {
                "player": query,
                "predicted_points": 0,
                "news": "Player not found",
                "advice": "Please retrain the ML model."
            }
            
        data = feature_engineering(found);
        data_imputed = imputer.transform(data[feature_cols])
        data_imputed = pd.DataFrame(data_imputed, columns=feature_cols)
        
        return {
            "player": query,
            "predicted_points": round(model.predict(data_imputed)[0]),
            "news": "Model loaded successfully",
            "advice": "Good choice"
        }
    except EOFError:
        return {
            "player": query,
            "predicted_points": 5,
            "news": "Fallback: Model file is empty.",
            "advice": "Please retrain the ML model."
        }
    except Exception as e:
        return {
            "player": query,
            "predicted_points": 0,
            "news": "Error loading model",
            "advice": str(e)
        }

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="FPL Intel — predict player points")
    parser.add_argument("csv", nargs="?", default="abort!!!", help="Path to .csv")
    args = parser.parse_args()

    CSV_PATH = args.csv

    if CSV_PATH == "abort!!!":
        raise ValueError("You must specify a CSV path")

    print("=" * 62)
    print(" Loading model...")
    print("=" * 62)

    with open(MODEL_PATH, "rb") as f:
        bundle = pickle.load(f)

    model        = bundle["model"]
    imputer      = bundle["imputer"]
    FEATURE_COLS = bundle["feature_cols"]
    model_name   = bundle["model_name"]
    metrics      = bundle["metrics"]

    print(f"  Model      : {model_name}")
    print(f"  MAE        : {metrics['MAE']:.3f} pts")
    print(f"  RMSE       : {metrics['RMSE']:.3f} pts")
    print(f"  R2         : {metrics['R2']:.3f}")
    print(f"  Features   : {len(FEATURE_COLS)}")

    print("\n" + "=" * 62)
    print(f" loading CSV")
    print("=" * 62)

    df = pd.read_csv(CSV_PATH)
    print(f"  Total players in CSV : {len(df)}")

    missing = [c for c in FEATURE_COLS if c not in df.columns]
    if missing:
        raise ValueError(
            f"CSV is missing {len(missing)} feature column(s): {missing}\n"
            f"Make sure you generated this CSV using features.py from the same pipeline."
        )

    print("\n" + "=" * 62)
    print(" Running predictions...")
    print("=" * 62)

    X = df[FEATURE_COLS].copy()
    for col in FEATURE_COLS:
        X[col] = pd.to_numeric(X[col], errors="coerce")

    X_imputed   = imputer.transform(X.values)
    X_df        = pd.DataFrame(X_imputed, columns=FEATURE_COLS)
    predictions = model.predict(X_df)
    print(f"  Done — {len(predictions)} predictions made")

    print("\n" + "=" * 62)
    print(f" PREDICTIONS  ({model_name})")
    print("=" * 62)
    print(f"{'#':<3} {'Player':<18} {'Team':<6} {'Pos':<5} {'Price':>6} {'Actual':>8} {'Predicted':>10} {'Diff':>7}")
    print("-" * 62)

    for i, (_, row) in enumerate(df.iterrows()):
        pred   = predictions[i]
        actual = row.get("total_points", float("nan"))
        diff   = pred - actual if not np.isnan(actual) else float("nan")
        sign   = "+" if (not np.isnan(diff) and diff >= 0) else ""
        diff_str   = f"{sign}{diff:>6.1f}" if not np.isnan(diff) else "   N/A"
        actual_str = f"{actual:>8.0f}"     if not np.isnan(actual) else "     N/A"

        print(
            f"{i+1:<3} "
            f"{row['web_name']:<18} "
            f"{row['short_name']:<6} "
            f"{row['position_name']:<5} "
            f"£{row['price']:>5.1f} "
            f"{actual_str} "
            f"{pred:>10.1f} "
            f"{diff_str}"
        )

    print("-" * 62)
    print("\n  Predicted = what the model thinks the player will score")
    print("  Actual    = what they actually scored this season")
    print("  Diff      = how far off the model was (+ over, - under)")
