"""
FPL Intel — Load Model & Predict Rolling xP (Expected Next-GW Points)

Uses feature_engineering() to build per-player features, then predicts
rolling expected points (xP) using the trained XGBoost model.
"""
import sqlite3
import argparse
import pickle
import warnings
import numpy as np
import pandas as pd
import os

from ml.features import feature_engineering
warnings.filterwarnings("ignore")

# Point to the model generated by train.py at the project root
MODEL_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "models", "fpl_xgboost.pkl"))


# ─── ADVICE CLASSIFICATION ───────────────────────────────────────────────────
# Thresholds are per-position since GKP/DEF score differently than MID/FWD

ADVICE_THRESHOLDS = {
    "GKP": {"elite": 5.0, "good": 3.5, "bench": 2.0},
    "DEF": {"elite": 5.5, "good": 3.5, "bench": 2.0},
    "MID": {"elite": 6.0, "good": 4.0, "bench": 2.5},
    "FWD": {"elite": 6.5, "good": 4.5, "bench": 2.5},
}


def classify_advice(xp: float, position: str, has_injury: int, is_available: bool) -> str:
    """
    Generate actionable FPL advice based on predicted xP, position, and status.

    Returns one of:
        🟢 Strong Start — elite xP for position
        ✅ Good Start   — above-average xP
        🟡 Bench        — mediocre xP, risky start
        🔴 Avoid        — low xP or injured/unavailable
    """
    if has_injury == 1 or not is_available:
        return "🔴 Avoid — Injury/availability concern"

    thresholds = ADVICE_THRESHOLDS.get(position, ADVICE_THRESHOLDS["MID"])

    if xp >= thresholds["elite"]:
        return "🟢 Strong Start — High expected returns"
    elif xp >= thresholds["good"]:
        return "✅ Good Start — Solid pick this GW"
    elif xp >= thresholds["bench"]:
        return "🟡 Bench — Consider alternatives"
    else:
        return "🔴 Avoid — Low expected output"


def predict_points(query):
    """
    Predict rolling expected points (xP) for a player mentioned in the query.
    Returns a dict with player name, xP, news, and advice classification.
    """
    try:
        with open(MODEL_PATH, "rb") as f:
            bundle = pickle.load(f)
        
        model        = bundle["model"]        # Pipeline (StandardScaler + XGBoost)
        feature_cols = bundle["feature_cols"]  # Expected feature columns
        imputer      = bundle["imputer"]       # Imputer for missing values
        
        conn = sqlite3.connect("fpl_intel.db")
        player_rows = pd.read_sql(
            "SELECT web_name, chance_of_playing_next_round, news FROM players WHERE minutes > 0", conn
        )
        conn.close()
        
        # --- Better player matching: check if query contains any player name ---
        query_lower = query.lower()
        found = ""
        best_len = 0
        for name in player_rows["web_name"].values:
            if name.lower() in query_lower and len(name) > best_len:
                found = name
                best_len = len(name)  # Pick longest match (e.g., "B.Fernandes" over "Fern")

        if found == "":
            return {
                "player": query,
                "predicted_points": None,
                "news": "Player not found in database.",
                "advice": "Try searching by the player's FPL web name (e.g., Salah, Haaland, Saka)."
            }
            
        data = feature_engineering(found)

        # Handle missing columns gracefully
        for col in feature_cols:
            if col not in data.columns:
                data[col] = 0

        data_imputed = imputer.transform(data[feature_cols])
        data_imputed = pd.DataFrame(data_imputed, columns=feature_cols)
        
        xp = round(model.predict(data_imputed)[0], 1)
        xp = max(0, xp)  # Clamp negative predictions

        # Get player metadata for advice classification
        player_info = player_rows[player_rows["web_name"] == found].iloc[0]
        has_injury = int(data.get("has_injury_news", pd.Series([0])).iloc[0])
        chance = player_info.get("chance_of_playing_next_round")
        is_available = (chance if chance is not None and not pd.isna(chance) else 100) >= 75
        position = str(data.get("position_name", pd.Series(["MID"])).iloc[0])

        advice = classify_advice(xp, position, has_injury, is_available)
        
        return {
            "player": found,
            "predicted_points": xp,
            "news": f"Expected {xp} pts next GW based on form, fixtures, and historical performance.",
            "advice": advice
        }
    except EOFError:
        return {
            "player": query,
            "predicted_points": None,
            "news": "Model file is empty or corrupted.",
            "advice": "Please retrain the ML model: python ml/train.py"
        }
    except Exception as e:
        return {
            "player": query,
            "predicted_points": None,
            "news": "Error loading model",
            "advice": str(e)
        }

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="FPL Intel — predict player xP")
    parser.add_argument("csv", nargs="?", default="abort!!!", help="Path to .csv")
    args = parser.parse_args()

    CSV_PATH = args.csv

    if CSV_PATH == "abort!!!":
        raise ValueError("You must specify a CSV path")

    print("=" * 62)
    print(" Loading model...")
    print("=" * 62)

    with open(MODEL_PATH, "rb") as f:
        bundle = pickle.load(f)

    model        = bundle["model"]
    imputer      = bundle["imputer"]
    FEATURE_COLS = bundle["feature_cols"]
    model_name   = bundle["model_name"]
    metrics      = bundle["metrics"]

    print(f"  Model      : {model_name}")
    print(f"  MAE        : {metrics['MAE']:.3f} pts")
    print(f"  RMSE       : {metrics['RMSE']:.3f} pts")
    print(f"  R2         : {metrics['R2']:.3f}")
    print(f"  Features   : {len(FEATURE_COLS)}")

    print("\n" + "=" * 62)
    print(f" loading CSV")
    print("=" * 62)

    df = pd.read_csv(CSV_PATH)
    print(f"  Total players in CSV : {len(df)}")

    missing = [c for c in FEATURE_COLS if c not in df.columns]
    if missing:
        raise ValueError(
            f"CSV is missing {len(missing)} feature column(s): {missing}\n"
            f"Make sure you generated this CSV using features.py from the same pipeline."
        )

    print("\n" + "=" * 62)
    print(" Running predictions...")
    print("=" * 62)

    X = df[FEATURE_COLS].copy()
    for col in FEATURE_COLS:
        X[col] = pd.to_numeric(X[col], errors="coerce")

    X_imputed   = imputer.transform(X.values)
    X_df        = pd.DataFrame(X_imputed, columns=FEATURE_COLS)
    predictions = model.predict(X_df)
    predictions = np.clip(predictions, 0, 15)  # Clamp to reasonable range
    print(f"  Done — {len(predictions)} predictions made")

    print("\n" + "=" * 62)
    print(f" PREDICTIONS  ({model_name})")
    print("=" * 62)
    print(f"{'#':<3} {'Player':<18} {'Team':<6} {'Pos':<5} {'Price':>6} {'xP':>8} {'Advice'}")
    print("-" * 72)

    for i, (_, row) in enumerate(df.iterrows()):
        pred = predictions[i]
        pos = row.get("position_name", "MID")
        has_inj = int(row.get("has_injury_news", 0))
        advice = classify_advice(pred, pos, has_inj, True)

        print(
            f"{i+1:<3} "
            f"{row['web_name']:<18} "
            f"{row['short_name']:<6} "
            f"{row['position_name']:<5} "
            f"£{row['price']:>5.1f} "
            f"{pred:>8.1f} "
            f"{advice}"
        )

    print("-" * 72)
    print("\n  xP = Expected points for the NEXT gameweek")
    print("  Based on per-90 rates, form, fixture difficulty, and availability")
